### ISSUE TITLE
Upload broken in Firefox

### ISSUE THREAD

**Issue by neuhaus** [kern/filepizza#56]
I try to upload a file on Firefox 48 on Linux.

It stays at "Processing" indefinitely.

When looking at the javascript console I see two errors:

a) Firefox can't establish a connection to server wss://file.pizza/socket.io/?EIO=3&transport=websocket&sid=nyeb40GlD7oFHVhZAGQU js:32:4398
POST 
XHR 
https://file.pizza/socket.io/ [HTTP/2.0 200 OK 178ms]
GET 
XHR 
https://file.pizza/socket.io/ [HTTP/2.0 200 OK 19107ms]
Error: Invalid torrent identifier

**Comment by kern** [comment]
Not able to replicate this. I've upgraded WebTorrent which might fix the issue. Can you try again @neuhaus?

**Comment by neuhaus** [comment]
Please have a look at my comments in issue #55. I still have an issue with uploading in firefox and downloading with chrome or opera on Linux.

**Comment by neuhaus** [comment]
Let me know what and how to test specifially if you need something to understand the exact issue.

**Comment by kern** [comment]
Should be working now, was an issue with how I set up my webserver to forward WebSockets. I disabled SocketIO's websocket transport (not really necessary since the number of messages sent is extremely small) and it works like a charm. Thanks for the report!

I'm happy to reopen this issue if it still persists.

Also closes #55.
