### ISSUE TITLE
FilePizza does not load

### ISSUE THREAD

**Issue by anonsubmitter** [kern/filepizza#64]
I tried to send a .zip file to a friend yesterday. I distributed the file via Google Chrome on Windows 7 and he tried to download it via Mozilla Firefox and Google Chrome and it didn't load. We both had WebRTC activated.
Today I tried to upload a .txt file from my Android phone's Chrome app and download it via Mozilla Firefox on a Windows 10 computer, but that didn't load either. Both browsers had WebRTC activated.

**Comment by kern** [comment]
Hi @anonsubmitter, any errors in the console?

**Comment by sakubara** [comment]
I've experienced that problem too. Sent the link given by file.pizza to my friend and he wasn't able to load the file. We tried Firefox and Chrome. I noticed that in Firefox under about:webrtc it was shown that Firefox tried to use the internal IP to establish a connection. It was something like 192.168.x.x.

**Comment by tutume** [comment]
same scenario as the first post in this thread. Made tests with
https://test.webrtc.org/
[ INFO ] Gathered candidate of Type: srflx Protocol: udp Address: x.x.x.x
[ INFO ] Gathered candidate of Type: srflx Protocol: udp Address: x.x.x.x
[ WARN ] Could not connect using reflexive candidates, likely due to the network environment/configuration.

Is that something relevant for this issue?

It worked with https://www.sharedrop.io

**Comment by kern** [comment]
not able to replicate, please reopen if issues persist
