### ISSUE TITLE
Large downloads failing

### ISSUE THREAD

**Issue by cpollock** [kern/filepizza#8]
![Failed Download](https://cloud.githubusercontent.com/assets/2078707/7643006/7c0f9220-fa63-11e4-8af5-a52165d6ee63.png)

I'm not sure what the threshold is for failed downloads, but I received this error twice today while trying to transfer a couple of zips.  One was 200mb the other was 500, both times the transfer looked fine, but once the file had been delivered the download would fail with the following error message:
"The server could not find the file"

Chrome 42, OSX Yosemite

**Comment by kern** [comment]
Chrome has issues with blobs >500mb due to an outstanding issue (https://code.google.com/p/chromium/issues/detail?id=375297). Are you experiencing the same error with the 200mb file?

Can't reproduce this locally for files ~200mb.

If so, it might have to do with the `download()` hook of [DownloadFile.js](https://github.com/kern/filepizza/blob/master/lib/DownloadFile.js). We asynchronously revoke the object URL of the file immediately after triggering the download, but that may result in the blob deallocating before being downloaded. Perhaps try deleting line 40 of that file and see if it works? Might have to lengthen the timeout before revoking it.

**Comment by cpollock** [comment]
Just checked, both files were above 500mb.  Might be a good idea to show a message if a file is above that limit and the receivers browser is Chrome.

**Comment by n4ru** [comment]
Could try splitting the blobs and rejoining them once the download completes.

**Comment by kern** [comment]
Thanks for the suggestion! I've added a note in 31adc4533393f4e1445241db78f556edd8416ec6 regarding the issues Chrome has for files > 500 MB.
